package com.dto;

import lombok.Data;

    @Data
    public class AuthRequest {
        private String username;
        private String password;
        // getters/setters generated by Lombok
    }


